name: educoresystem
description: EduCore System
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core:
  firebase_auth:
  cloud_firestore:
  provider:
  intl:
  google_fonts:
  fl_chart:
  pdf:
  printing: ^5.15.0
  path_provider:
  image_picker:
  flutter_image_compress:
  image_picker_web:
  image:
  shared_preferences:
  shimmer:
  open_file:
  universal_platform:
  share_plus:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/EducoreLogo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/EducoreLogo.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/EducoreLogo.png"
  android: true
  ios: true
  web: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/