name: educoresystem
description: EduCore System
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core:
  firebase_auth:
  cloud_firestore:
  provider:
  intl:
  google_fonts:
  fl_chart:            # reports ke liye (optional)
  pdf:                  # PDF reports ke liye (optional)
  printing:             # PDF print/share ke liye (optional)
  path_provider:         # PDF save karne ke liye (optional)
  image_picker:
  flutter_image_compress:
  image_picker_web:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  # assets add kar sakte ho agar koi image chahiye