// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLXhmhf4L7oy0xCt9sb4gWGLKF4o1MnEU',
    appId: '1:449935855868:web:6a7c304e1575567b3c4779',
    messagingSenderId: '449935855868',
    projectId: 'educationcoresystem',
    authDomain: 'educationcoresystem.firebaseapp.com',
    storageBucket: 'educationcoresystem.firebasestorage.app',
    measurementId: 'G-L1XMF0TRC9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaPMaC8Ltk_WIk8VO2yxMEKHScNPTUeQs',
    appId: '1:449935855868:android:d3aacbded3bf2d2f3c4779',
    messagingSenderId: '449935855868',
    projectId: 'educationcoresystem',
    storageBucket: 'educationcoresystem.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFDzB5aUFtA_oeI-piNhAMgVozexpFuiI',
    appId: '1:449935855868:ios:f29655e69dec89753c4779',
    messagingSenderId: '449935855868',
    projectId: 'educationcoresystem',
    storageBucket: 'educationcoresystem.firebasestorage.app',
    iosBundleId: 'com.example.educoresystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFDzB5aUFtA_oeI-piNhAMgVozexpFuiI',
    appId: '1:449935855868:ios:f29655e69dec89753c4779',
    messagingSenderId: '449935855868',
    projectId: 'educationcoresystem',
    storageBucket: 'educationcoresystem.firebasestorage.app',
    iosBundleId: 'com.example.educoresystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLXhmhf4L7oy0xCt9sb4gWGLKF4o1MnEU',
    appId: '1:449935855868:web:d9e59bc07b6779c33c4779',
    messagingSenderId: '449935855868',
    projectId: 'educationcoresystem',
    authDomain: 'educationcoresystem.firebaseapp.com',
    storageBucket: 'educationcoresystem.firebasestorage.app',
    measurementId: 'G-1D64DZRLNZ',
  );
}
